config/routes.rb
Watt::Application.routes.draw do

  resources :locations

  resources :projects do
    member do
      get :vote
      get :search_by_tag
    end
  end

  resources :comments do
    member do
      get :vote
    end
  end

  devise_for :users,  :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  devise_for :users do get '/users/sign_in' => 'devise/sessions#new' end
  devise_for :users do get '/users/edit/:id' => 'devise/registrations#edit' end
  resources :users, :only => [:edit,:update, :show]

  get "tags/:tag" => "projects#index, as: :tag"

  match "/search/tags_list" => "projects#search_by_tags"

  get "static_pages/home"

  get "static_pages/profile"

  get "static_pages/participate"

  get "static_pages/submit_project"

  get "static_pages/research"

  get "static_pages/evaluate"

  get "static_pages/design"

  get "static_pages/finalize"

  get "static_pages/browse_investments"

  get "static_pages/install"

  get "static_pages/earn"

  get "static_pages/learn_more"

  get "static_pages/how_watt_works"

  get "static_pages/blog"

  get "static_pages/about"

  get "static_pages/search"

  get "static_pages/signup"

  get "static_pages/login"

  devise_for :users

  root :to => 'static_pages#home'
end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_taggable
  acts_as_commentable
  acts_as_voteable
  acts_as_gmappable
  attr_accessible :address, :idea, :problem, :solution, :user_id, :zipcode, :tag_list, :image, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?


  validates_attachment :image,# presence: true,
                               content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                               size: { less_than: 5.megabytes }

  belongs_to :user
  #default_scope -> { order(@project.karma) }
  has_attached_file :image #, styles: { medium: "320x240>"}

  validates :user_id, presence: true
  validates :idea, presence: true
  validates :problem, presence: true
  validates :solution, presence: true
  
  default_scope order: 'projects.created_at DESC'

  def karma
    self.votes_for - self.votes_against
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def vote
    give_vote(params, 'Project')
  end

  def search_by_tags
    if params[:q].present?
      sql = "select * from tags where LOWER(name) LIKE "  + "'" + params[:q].downcase.to_s + "%%'" +""
      result = ActiveRecord::Base.connection.execute(sql)
      @tags = result.to_a
      @tags = @tags.flatten

      respond_to do |format|
        format.json { render :json => @tags }
      end
    end
  end

  def index
    #  @projects = params[:id].blank? ? Project.all : Project.where("user_id=?",params[:id])
    #@locations = Location.all

    if params[:tag]
      @projects = params[:id].blank? ? Project.tagged_with(params[:tag]) : Project.tagged_with(params[:tag]).where("user_id=?",params[:id])
    else
      @projects = params[:id].blank? ? Project.all : Project.where("user_id=?",params[:id])
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end

    # @location = Location.find(params[:id])

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render json: @location }
    # end
  end


  def new
    @project = current_user.projects.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end

    #@location = Location.new

  end

  def edit
    @project = current_user.projects.find(params[:id])
  end

  def create
    @project = current_user.projects.build(params[:project])
    #@location = Location.new(params[:location])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @project = current_user.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>
  <%= f.full_error :address, class: "alert alert-error" %>
  

  <div class="form-inputs">
    <br>
    <%= f.input :idea, label: 'Clean Energy Project Idea Discription', placeholder: "I want to put solar panels on my roof." %>
    <br>
    <%= f.input :address, label: 'Project Location Address', placeholder: "123 Main Street, 10001 USA" %>
    <br>
    <%#= f.input :zipcode, label: 'Zip Code Where The Project Is Located', placeholder: "12345" %>
    
    <%= f.input :problem, label: 'What Is The Problem You Are Trying To Solve?', placeholder: "The problems is that..." %>
    <br>
    <%= f.input :solution, label: 'What Is Your Suggested Solution To The Problem?', placeholder: "I believe the solution is..." %>
    <br>
    <%= f.input :image, label: "Attach files", :class => "btn btn-large btn-success" %>
    
    <%#= f.input :tag_list, label: "Tags (separated by commas)", placeholder: "Enter Tags"  %>


    <%#*<div style="float: left;width: 100%;">%>
      <%#*<div id="video_search_by_tags" style="float:left; width:auto; padding-top: 10px; margin-top: 8px; margin-bottom: 8px;">%>
        <%#*<input type="text" id="demo-input-facebook-theme" name="tags_list" />%>
      <%#*</div>%>
    <%#*</div>%>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#demo-input-facebook-theme").tokenInput("/search/tags_list", {
          theme: "facebook",
          prePopulate: [<%= raw (params[:tags_list].split(',').collect{ |tag_name| "{name : '#{tag_name}'  }" }.join(',')) unless params[:tags_list].blank? %>],
          tokenValue: 'name',
          preventDuplicates:  true,
          hintText: "Search tags",
          noResultsText: "no tag found",
          searchingText: "Searching tags ..."
        });
      });
    </script>
  </div>

  
    <%= f.button :submit, class: "btn btn-large btn-block btn-success" %>
 
<% end %>

app/views/projects/edit.html.erb
<div class="row-fluid">
  <div class="span10 offset1">
		<div class="hero-unit">
			
			<div class="pull-left">
				<%= link_to 'Back To Projects', projects_path, class: "btn btn-success" %>
			</div>
			
			<div class="pull-right">
		    <%= link_to 'View This Project', @project, class: "btn btn-success" %>
		  </div>

		  <br>
		  <br>

			<h2>Edit Your Clean Energy Project</h2>
			<% if @project.image.present?%>
		    <%= image_tag @project.image, :class => "img-rounded" %>
		  <%else%>
		    
		  <%end%> 

			<%= render 'form' %>

			<br>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<div class="row-fluid">
  <div class="span10 offset1">
    <h1>Clean Energy Projects</h1>
    <div class="pull-left">
      <%= link_to 'Submit New Project Idea', new_project_path, class: "btn btn-success" %><br>
    </div>

    <br>

    <table class="table table-hover table-condensed">
      <thead class="strong">
        <tr>
          <!-- <th>Project Number</th> -->
          <th>Influence</th>
          <th>Creator</th>
          <th>Clean Energy Project Idea</th>
          <!-- <th>Address</th>
          <th>Zipcode</th>
          <th>Problem</th>
          <th>Solution</th>
          <th>Attachments</th>
          <th>Tags</th> -->
          <th>Created</th>
          <th></th>
          <th></th>
          <th></th>   
        </tr>
      </thead>

      <% @projects.each do |project| %>
        <tr>
          <!-- <td>
            <%#= project.id %>
          </td> -->
          <td>
            <div id='<%= "voting_#{project.class.to_s}_#{project.id}" %>'>
              <%= render :partial => "shared/voting", :locals => {:object => project} %>
            </div>
          </td>
          
          <td><%= link_to project.user.name, projects_path(:id => project.user.id) %></td>
          
          <td onclick="location.href='<%= project_path(project) %>'"><%= project.idea %></td>
          
          <!-- <td><%= project.address %></td>
          <td><%= project.zipcode %></td>
          
          <td><%= project.problem %></td>
          
          <td><%= project.solution %></td>
          
          <% if project.image.present? %>
            <td>Yes</td>
          <% else %>
            <td> None </td>
          <% end %>
          
           <%if project.tag_list.present?%>
            <td><%= raw project.tag_list.map { |t| link_to t}.join(",")%></td>
          <%else%>
            <td> None </td>
          <%end%> -->
          
          <td><%= time_ago_in_words(project.created_at) %> ago</td>
          <td><%= link_to 'Influence', project, class: "btn btn-mini btn-primary" %></td>

          <% if current_user == project.user %>
            <td><%= link_to 'Edit', edit_project_path(project), class: "btn btn-mini btn-warning" %></td>
            <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
          <% end %>
          
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<!--New Project-->

<% if user_signed_in? %>
	<div class="row-fluid">
	  <div class="span10 offset1">	
		
			<div class="hero-unit">
				<h2><%= current_user.name %>, bring your clean energy project to life!
				Please fill out the following with as much detail as you can.</h2>
				
					<%= render 'form' %>
				
			</div>
		</div>
	</div>

<% else %>

	<div class="container">
		<form class="form-signin">
			<legend>Please Plug-In to Play</legend>
			<ul>
				
				<li class="btn btn-large btn-block btn-success plug_in_to_play">
					<%= link_to("Sign Up", new_user_registration_path) %>
				</li>
				
				<br>
				
				<li class="btn btn-large btn-block btn-success plug_in_to_play">
					<%= link_to("Plug In", new_user_session_path)%>
				</li>
				
			</ul>
		</form>
	</div>
<% end %>

app/views/projects/show.html.erb
<!--Show Project-->
<div class="row-fluid">
  <div class="span10 offset1">
    <div class="hero-unit">
      <div class="pull-left">
        <%= link_to 'Back To Projects', projects_path, class: "btn btn-success" %>
      </div>
      <div class="pull-right">  
        <% if current_user == @project.user %>
          <%= link_to 'Edit This Project', edit_project_path(@project), class: "btn btn-warning" %>
        <% end %>
      </div>
      <br>
      <br>


      <div id='<%= "voting_#{@project.class.to_s}_#{@project.id}" %>'>
        <%= render :partial => "shared/voting", :locals => {:object => @project} %>
      </div>


      <table>
        <p>
          <b>Project Creator:</b>
          <%#= link_to @project.user.name, user_path(@project.user) %>
          <%= link_to @project.user.name, projects_path(:id => @project.user.id) %>
        </p>
        <p>
          <b>Idea:</b>
          <%= @project.idea %>
        </p>
        <%#= image_tag "http://maps.google.com/maps/api/staticmap?size=650x650&scale=1&maptype=satellite&sensor=false&zoom=20&markers=#{@location.latitude}%2C#{@location.longitude}" %>
        <!-- <p>
          <b>Address:</b>
          <%#= @project.address %>
        </p>
        <p>
          <b>Zipcode:</b>
          <%#= @project.zipcode %>
        </p> -->
        <p>
          <b>Problem:</b>
          <%= @project.problem %>
        </p>
        <p>
          <b>Solution:</b>
          <%= @project.solution %>
        </p>
        <p>
          <b>Attachments:</b>
          <% if @project.image.present?%>
            <%= image_tag @project.image, :class => "img-rounded" %>
          <%else%>
            None
          <%end%> 
        </p>
        <p>
          <b>Created:</b>
          <%= time_ago_in_words(@project.created_at) %> ago.
        </p>
        <p>
          <b>Tags:</b>
          <%if @project.tag_list.present?%>
            <%= raw @project.tag_list.map { |t| link_to t}.join(",")%>
          <%else%>
            None
          <%end%>
        </p>
      </table>



    <!-- This is the first tier comments posting section -->



      <%= simple_form_for(@comment, :remote  => true) do |f| %>
        <%= f.full_error :image_file_size, class: "alert alert-error" %>
        <%= f.full_error :image_content_type, class: "alert alert-error" %>
        <%= hidden_field_tag "project_id", @project.id %>
        <%= f.hidden_field :commentable_id, :value => @project.id %>
        <%= f.hidden_field :commentable_type, :value => 'Project' %>
        <%= f.label :comment %><br />
        <%= f.text_area :comment, :size => "width: 450px", :class => "comment_text_area" %>
        
    <!-- this is where I need to add attachments for comments -->
        
        <div class="inputs">
          <%#= f.input :image, label: "Attach Files! (Get visual! Attachments must be under 5MB, and only images ending in .JPG, .GIF, and .PNG will appear in thumbnail form)" %>
        </div>

        <br> 
        <div>
          <%= f.button :submit, class: "btn btn-large btn-success" %>
        </div>
      <% end %>



      <div id="all_comments">
        <% comments = @project.comments.order("created_at asc") %>

            <% unless comments.blank? %>
              <% comments.each do |comment| %>
              <% if @comment.image.present?%>
                <%= image_tag @comment.image(:medium), :class => "img-rounded" %>
              <%else%>
                
              <%end%> 
            <%= render :partial => "projects/partials/comment", :locals => {:comment => comment, :user_id => current_user.id, :project_id => @project.id } %>
          <% end%>
        <% else %>
          Be the first to influence this project!
        <% end %>
      </div>

      
      <br>
      <br>
    </div>
  </div>
</div>