config/routes.rb
Watt::Application.routes.draw do

  resources :locations

  resources :projects do
    member do
      get :vote
      get :search_by_tag
    end
  end

  resources :comments do
    member do
      get :vote
    end
  end

  devise_for :users,  :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  devise_for :users do get '/users/sign_in' => 'devise/sessions#new' end
  devise_for :users do get '/users/edit/:id' => 'devise/registrations#edit' end
  resources :users, :only => [:edit,:update, :show]

  get "tags/:tag" => "projects#index, as: :tag"

  match "/search/tags_list" => "projects#search_by_tags"

  get "static_pages/home"

  get "static_pages/profile"

  get "static_pages/participate"

  get "static_pages/submit_project"

  get "static_pages/research"

  get "static_pages/evaluate"

  get "static_pages/design"

  get "static_pages/finalize"

  get "static_pages/browse_investments"

  get "static_pages/install"

  get "static_pages/earn"

  get "static_pages/learn_more"

  get "static_pages/how_watt_works"

  get "static_pages/blog"

  get "static_pages/about"

  get "static_pages/search"

  get "static_pages/signup"

  get "static_pages/login"

  devise_for :users

  root :to => 'static_pages#home'
end

app/views/layouts/partials/_footer.html.erb
<footer class="footer fixed-bottom">
  <nav>
    <ul>
      <li><%= link_to "Browse Investments", browse_investments_path %></li>
      <li><%= link_to "Participate", participate_path %></li>
      <li><%= link_to "Submit A Project", submit_project_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><%= link_to "Careers", '#' %></li>
      <li><%= link_to "News", '#' %></li>
      <li><%= link_to "Terms & Conditions", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/partials/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <div class="row-fluid">
        <div class="span10 offset1">

          <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <!-- Be sure to leave the brand out there if you want it shown -->

          <%= link_to image_tag("logo.png", :height => "40", :width => "120", :class => "brand"), projects_path  %>

          <!-- Everything you want hidden at 940px or less, place within here -->
          <div class="nav-collapse collapse  navbar-responsive-collapse">

            <!-- .nav, .navbar-search, .navbar-form, etc -->

            <ul class="nav pull-right">

              <!-- Investments -->
              <li>
                <%#= link_to("Browse Projects", projects_path) %>
              </li>
              
              <li>
                <% if user_signed_in? %>
                  <%= link_to("Browse Investments", projects_path) %>
                <% else %> 
                  <%= link_to("Browse Investments", new_user_registration_path) %>
                <% end %> 
              </li>

              <!-- Participate Dropdown Menu -->

              <li class="dropdown">
                <a href="/participate" class="dropdown-toggle" data-toggle="dropdown">
    				      Influence
                  <b class="caret"></b>
                </a>

                <ul class="dropdown-menu">
                  <li>
                    <a href="<%= projects_path %>" >
                      <i class="icon-book"/></i>
    									Research A Project<br>
                      <h6>Vote and collaborate on new projects</h6>
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="<%= projects_path %>">
                      <i class="icon-pencil"/></i>
    									Design A Project<br>
                      <h6>Help bring chosen projects to life</h6>
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="<%= projects_path %>">
                      <i class="icon-flag"/></i>
    									Finalize A Project<br>
                      <h6>Help put the final touches on projects</h6>
                    </a>
                  </li>
                </ul>
              </li>

              <!-- Submit Project Idea -->

              <li class="btn btn-success submit_btn">
                <%= link_to("Submit A Project Idea", new_project_path) %>
              </li>

              <!-- Learn More Dropdown Menu -->

              <li class="dropdown">
                <a href="/learn_more" class="dropdown-toggle" data-toggle="dropdown">
    				      Learn More
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="<%= static_pages_how_watt_works_path %>">
                      <i class="icon-cog"/></i>
    									How WA.TT Works<br>
                      <h6>Clean energy project creation explained</h6>
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="/blog">
                      <i class="icon-bullhorn"/></i>
    									Blog<br>
                      <h6>Check out what we are working on</h6>
                    </a>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <a href="<%= static_pages_about_path %>">
                      <i class="icon-off"/></i>
    									About Us<br>
                      <h6>Come meet the WA.TT team</h6>
                    </a>
                  </li>
                </ul>
              </li>

              <!-- Search Box

    					<li>
    						<form class="navbar-search pull-left" action="">
    							<input type="text" class="search-query span2" placeholder=""/>
    						</form>
    					</li>
    					-->
              <li>
                &nbsp&nbsp&nbsp&nbsp
              </li>
              <!-- Sign up/in/out -->

              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="/profile" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_user.name %>
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">

                    <li>
                      <a href="<%= edit_user_registration_path %>">
                        Welcome,&nbsp&nbsp<%= current_user.name %>!
                      </a>
                    </li>

                    <li class="divider"></li>

                    <li>
                      <a href="<%= projects_path(:id => current_user.id) %>">
                        <i class="icon-heart"/></i>
                        My Projects
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="icon-thumbs-up"/></i>
                        Influence
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="icon-signal"/></i>
                        Investments
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="icon-list-alt"/></i>
                        Account Balance
                      </a>
                    </li>

                    <li class="divider"></li>

                    <li>
                      <a href="#">
                        <i class="icon-envelope"/></i>
                        Inbox
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="icon-comment"/></i>
                        Forum
                      </a>
                    </li>

                    <li class="divider"></li>

                    <li>
                      <a href="<%= edit_user_registration_path %>">
                        <i class="icon-user"/></i>
                        Edit Profile
                      </a>
                    </li>

                    <li>
                      <a href="#">
                        <i class="icon-tasks"/></i>
                        Dashboard
                      </a>
                    </li>

                    <li class="divider"></li>

                    <li>
                      <a href="<%= destroy_user_session_path %>">
                        <i class="icon-eject"/></i>
                        Unplug (Log Out)
                      </a>
                    </li>

                  </ul>
                </li>

              <% else %>
                <!--
                                                      <li class="dropdown">
                                                              <a href="new_user_session_path" class="dropdown-toggle" data-toggle="dropdown">
                                                                      Plug In
                                                                      <b class="caret"></b>
                                                              </a>

                                                  <ul class="dropdown-menu">
                                                      <li>
                                                              <form class="form-horizontal">
                                                                                <div class="control-group">
                                                                                      <label class="control-label" for="inputEmail">Email</label>
                                                                                  <div class="controls">
                                                                                    <input type="text" id="inputEmail" placeholder="Email">
                                                                                  </div>
                                                                                </div>
                                                                                <div class="control-group">
                                                                                  <label class="control-label" for="inputPassword">Password</label>
                                                                                  <div class="controls">
                                                                                    <input type="password" id="inputPassword" placeholder="Password">
                                                                                  </div>
                                                                                </div>
                                                                                <div class="control-group">
                                                                                  <div class="controls">
                                                                                    <label class="checkbox">
                                                                                      <input type="checkbox"> Remember me
                                                                                    </label>
                                                                                    <button type="submit" class="btn btn-success btn-large btn-block">Plug In</button>
                                                                                  </div>
                                                                                </div>
                                                                              </form>
                                                                      </li>
                                                              </ul>
                                                      </li>
                -->


                <li>
                  <%= link_to("Plug In", new_user_session_path) %>
                </li>

                <li>
                  <%= link_to("Sign Up", new_user_registration_path) %>
                </li>

              <% end %>

            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>				

app/views/layouts/partials/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->